dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: egc-app3
  strategy: git
  api_key:
    secure: S0cdytgiTItJ05Pq2XVNTXvaOoh3hZbibRfHm/JGwXb8NRHZC2tLYtZUsorMqjI/bWk+Lj5dKzGXo+yr0QBa9EHEYvEfdTBYSQObVLlukNgG1qvkaFf06TzW+rzQ9BDhaGET7YzUr2ecoZOSfjmwlbD7BZw8TSFdxvwJROnOgupGMpWbRCpiDI7163Mr23RNhya7iEBe/RXELTVoKtA7Law279WcJV2FMp6EnYBfEMvdDbhaUddczNseQbFtfUzdOxB1rGR08FZJj/7v74bIdi+2PQUD9zfA4TOKCz8YWFwi4xl3OZ2XHHC9vynUyEgSPPWlduWEWQALbexAC7xZvapPDZXlR7VgCqViSGx7kqOQR5iBv2affa8XbqeZ49Y58j7G3i02Kpypt7HXz+z8qd5aONqbRDNuSbPU7NfL9O111W394Q3K3+SFedMa8vP3mpCD280UVfBeBxDSHFbXmS03a5ewPOPV97S7yIyK3crvO51h8Ak2jhamMFsEO/KiHKtEGkqbEiWLFMJPzG0rJLSt6U99qNHtbgHfC30VY5JsYfSI8WCw6+Ps+om5bwo+CHu4ozvOSzOotwoJaw7BYPHhdVS30hYCLWImnsACbkChhCt49zm2fEWUhEYyuagpaX09cX7P1j1Mw9L50jbhz2fzWEMA0ZACeAwALcqAkdg=
