dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py test --keepdb
deploy:
  provider: heroku
  app: egc-app3
  strategy: git
  api_key:
    secure: aFwJsOR40zEeiALZGykbaLmDCtLo2DoeGxVciFQN9iWu8a7EVtXi7l0vB0AMkXZrKv8bsx1DB8s2tP9ZUIHYoVrXZ/Ep4jZJbZPrk+3jaSMiZxOwL2q/udqsyUiLeZBzD/LK29fvbYGHrPD2cvJ/6jWkNSCZThoL0gJbScm74tKfajGLn8L8MyeigirtPC1rLs3R6fVtJTulsa+W5XF2mTPBY+pwI7/uw/yjDZfkg7bJyAPoZXDHGgZfgvKBj+iJlk8d3/ppok6BjFETVoble/oCRdXnz0HKQ3wXLLRK34QY/iSVEkhKt5WGFIcXclTH3Exxwun1PqWTpfsKMzi16mNeAMcQOjZzlMOh6T1eTAkyjI1i5vdf57TqNmgKEUnMyP+gmnDDEDwld4gOmOeKrx4jb91xgTSYcHJI9G+GchdGaPY5e6iylekZGauVZsHltqmiqOfG0Yi/hP+t/sxqbtJ0epFBmgt45rhSgOsfJkTEylaSiQ6C0K+QYpyYt8CMDIr5Q1BqHZF6psnncz2f1darfmSCjAoOZz2mSIhO9tDdTLmvZpb3iCZ88JuIBP02vCfdvo52IUd4cmpg1DgvsH6xUNMebBoRLDFkEdBNyhx65SUcPVmYkpAYTH9Mptz+SXwih8XJPEYuD9pdKvSsKBlZxxSrobDVxUp2ZYh346c=
